var timezones = [
	["ACDT","Australian Central Daylight Time (UTC+10:30)",10.5],
	["ACST","Australian Central Standard Time (UTC+09:30)",9.5],
	["ACT","ASEAN Common Time (UTC+08)",8],
	["ADT","Atlantic Daylight Time (UTC-03)",-3],
	["AEDT","Australian Eastern Daylight Time (UTC+11)",11],
	["AEST","Australian Eastern Standard Time (UTC+10)",10],
	["AFT","Afghanistan Time (UTC+04:30)",4.5],
	["AKDT","Alaska Daylight Time (UTC-08)",-8],
	["AKST","Alaska Standard Time (UTC-09)",-9],
	["AMST","Armenia Summer Time (UTC+05)",5],
	["AMT","Armenia Time (UTC+04)",4],
	["ART","Argentina Time (UTC-03)",-3],
	["AST","Arab Standard Time (Kuwait, Riyadh) (UTC+03)",3],
	["AST","Arabian Standard Time (Abu Dhabi, Muscat) (UTC+04)",4],
	["AST","Arabic Standard Time (Baghdad) (UTC+03)",3],
	["AST","Atlantic Standard Time (UTC-04)",-4],
	["AWDT","Australian Western Daylight Time (UTC+09)",9],
	["AWST","Australian Western Standard Time (UTC+08)",8],
	["AZOST","Azores Standard Time (UTC-01)",-1],
	["AZT","Azerbaijan Time (UTC+04)",4],
	["BDT","Brunei Time (UTC+08)",8],
	["BIOT","British Indian Ocean Time (UTC+06)",6],
	["BIT","Baker Island Time (UTC-12)",-12],
	["BOT","Bolivia Time (UTC-04)",-4],
	["BRT","Brasilia Time (UTC-03)",-3],
	["BST","Bangladesh Standard Time (UTC+06)",6],
	["BST","British Summer Time (British Standard Time from Feb 1968 to Oct 1971) (UTC+01)",1],
	["BTT","Bhutan Time (UTC+06)",6],
	["CAT","Central Africa Time (UTC+02)",2],
	["CCT","Cocos Islands Time (UTC+06:30)",6.5],
	["CDT","Central Daylight Time (North America) (UTC-05)",-5],
	["CEDT","Central European Daylight Time (UTC+02)",2],
	["CEST","Central European Summer Time (Cf. HAEC) (UTC+02)",2],
	["CET","Central European Time (UTC+01)",1],
	["CHADT","Chatham Daylight Time (UTC+13:45)",13.75],
	["CHAST","Chatham Standard Time (UTC+12:45)",12.75],
	["CHOT","Choibalsan (UTC-08)",-8],
	["ChST","Chamorro Standard Time (UTC+10)",10],
	["ChST","Chamorro Standard Time (UTC+10)",10],
	["CHUT","Chuuk Time (UTC+10)",10],
	["CIST","Clipperton Island Standard Time (UTC-08)",-8],
	["CIT","Central Indonesia Time (UTC+08)",8],
	["CKT","Cook Island Time (UTC-10)",-10],
	["CLST","Chile Summer Time (UTC-03)",-3],
	["CLT","Chile Standard Time (UTC-04)",-4],
	["COST","Colombia Summer Time (UTC-04)",-4],
	["COT","Colombia Time (UTC-05)",-5],
	["CST","Central Standard Time (North America) (UTC-06)",-6],
	["CST","China Standard Time (UTC+08)",8],
	["CST","Central Standard Time (Australia) (UTC+09:30)",9.5],
	["CST","Central Summer Time (Australia) (UTC+10:30)",10.5],
	["CST","Cuba Standard Time (UTC-05)",-5],
	["CT","China time (UTC+08)",8],
	["CVT","Cape Verde Time (UTC-01)",-1],
	["CWST","Central Western Standard Time (Australia) (UTC+08:45)",8.75],
	["CXT","Christmas Island Time (UTC+07)",7],
	["DAVT","Davis Time (UTC+07)",7],
	["DDUT","Dumont d'Urville Time (UTC+07)",7],
	["DFT","AIX specific equivalent of Central European Time (UTC+01)",1],
	["EASST","Easter Island Standard Summer Time (UTC-05)",-5],
	["EAST","Easter Island Standard Time (UTC-06)",-6],
	["EAT","East Africa Time (UTC+03)",3],
	["ECT","Eastern Caribbean Time (does not recognise DST) (UTC-04)",-4],
	["ECT","Ecuador Time (UTC-05)",-5],
	["EDT","Eastern Daylight Time (North America) (UTC-04)",-4],
	["EEDT","Eastern European Daylight Time (UTC+03)",3],
	["EEST","Eastern European Summer Time (UTC+03)",3],
	["EET","Eastern European Time (UTC+02)",2],
	["EGST","Eastern Greenland Summer Time (UTC+00)",00],
	["EGT","Eastern Greenland Time (UTC-01)",-1],
	["EIT","Eastern Indonesian Time (UTC+09)",9],
	["EST","Eastern Standard Time (North America) (UTC-05)",-5],
	["EST","Eastern Standard Time (Australia) (UTC+10)",10],
	["FET","Further-eastern_European_Time (UTC+03)",3],
	["FJT","Fiji Time (UTC+12)",12],
	["FKST","Falkland Islands Summer Time (UTC-03)",-3],
	["FKT","Falkland Islands Time (UTC-04)",-4],
	["FNT","Fernando de Noronha Time (UTC-02)",-2],
	["GALT","Galapagos Time (UTC-06)",-6],
	["GAMT","Gambier Islands (UTC-09)",-9],
	["GET","Georgia Standard Time (UTC+04)",4],
	["GFT","French Guiana Time (UTC-03)",-3],
	["GILT","Gilbert Island Time (UTC+12)",12],
	["GIT","Gambier Island Time (UTC-09)",-9],
	["GMT","Greenwich Mean Time (UTC)",0],
	["GST","South Georgia and the South Sandwich Islands (UTC-02)",-2],
	["GST","Gulf Standard Time (UTC+04)",4],
	["GYT","Guyana Time (UTC-04)",-4],
	["HADT","Hawaii-Aleutian Daylight Time (UTC-09)",-9],
	["HAEC","Heure Avancée d'Europe Centrale francised name for CEST (UTC+02)",2],
	["HAST","Hawaii-Aleutian Standard Time (UTC-10)",-10],
	["HKT","Hong Kong Time (UTC+08)",8],
	["HMT","Heard and McDonald Islands Time (UTC+05)",5],
	["HOVT","Khovd Time (UTC+07)",7],
	["HST","Hawaii Standard Time (UTC-10)",-10],
	["ICT","Indochina Time (UTC+07)",7],
	["IDT","Israel Daylight Time (UTC+03)",3],
	["I0T","Indian Ocean Time (UTC+03)",3],
	["IRDT","Iran Daylight Time (UTC+08)",8],
	["IRKT","Irkutsk Time (UTC+08)",8],
	["IRST","Iran Standard Time (UTC+03:30)",3.5],
	["IST","Indian Standard Time (UTC+05:30)",5.5],
	["IST","Irish Summer Time (UTC+01)",1],
	["IST","Israel Standard Time (UTC+02)",2],
	["JST","Japan Standard Time (UTC+09)",9],
	["KGT","Kyrgyzstan time (UTC+07)",7],
	["KOST","Kosrae Time (UTC+11)",11],
	["KRAT","Krasnoyarsk Time (UTC+07)",7],
	["KST","Korea Standard Time (UTC+09)",9],
	["LHST","Lord Howe Standard Time (UTC+10:30)",10.5],
	["LHST","Lord Howe Summer Time (UTC+11)",11],
	["LINT","Line Islands Time (UTC+14)",14],
	["MAGT","Magadan Time (UTC+12)",12],
	["MART","Marquesas Islands Time (UTC-09:30)",-9.5],
	["MAWT","Mawson Station Time (UTC+05)",5],
	["MDT","Mountain Daylight Time (North America) (UTC-06)",-6],
	["MET","Middle European Time Same zone as CET (UTC+01)",1],
	["MEST","Middle European Saving Time Same zone as CEST (UTC+02)",2],
	["MHT","Marshall_Islands (UTC+12)",12],
	["MIST","Macquarie Island Station Time (UTC+11)",11],
	["MIT","Marquesas Islands Time (UTC-09:30)",-9.5],
	["MMT","Myanmar Time (UTC+06:30)",6.5],
	["MSK","Moscow Time (UTC+04)",4],
	["MST","Malaysia Standard Time (UTC+08)",8],
	["MST","Mountain Standard Time (North America) (UTC-07)",-7],
	["MST","Myanmar Standard Time (UTC+06:30)",6.5],
	["MUT","Mauritius Time (UTC+04)",4],
	["MVT","Maldives Time (UTC+05)",5],
	["MYT","Malaysia Time (UTC+08)",8],
	["NCT","New Caledonia Time (UTC+11)",11],
	["NDT","Newfoundland Daylight Time (UTC-02:30)",-2.5],
	["NFT","Norfolk Time[1] (UTC+11:30)",11.5],
	["NPT","Nepal Time (UTC+05:45)",5.75],
	["NST","Newfoundland Standard Time (UTC-03:30)",-3.5],
	["NT","Newfoundland Time (UTC-03:30)",-3.5],
	["NUT","Niue Time (UTC-11:30)",-11.5],
	["NZDT","New Zealand Daylight Time (UTC+13)",13],
	["NZST","New Zealand Standard Time (UTC+12)",12],
	["OMST","Omsk Time (UTC+06)",6],
	["ORAT","Oral Time (UTC-05)",-5],
	["PDT","Pacific Daylight Time (North America) (UTC-07)",-7],
	["PET","Peru Time (UTC-05)",-5],
	["PETT","Kamchatka Time (UTC+12)",12],
	["PGT","Papua New Guinea Time (UTC+10)",10],
	["PHOT","Phoenix Island Time (UTC+13)",13],
	["PHT","Philippine Time (UTC+08)",8],
	["PKT","Pakistan Standard Time (UTC+05)",5],
	["PMDT","Saint Pierre and Miquelon Daylight time (UTC+08)",8],
	["PMST","Saint Pierre and Miquelon Standard Time (UTC+08)",8],
	["PONT","Pohnpei Standard Time (UTC+11)",11],
	["PST","Pacific Standard Time (North America) (UTC-08)",-8],
	["PST","Philippine Standard Time (UTC+08)",8],
	["RET","Réunion Time (UTC+04)",4],
	["ROTT","Rothera Research Station Time (UTC-03)",-3],
	["SAKT","Sakhalin Island time (UTC+11)",11],
	["SAMT","Samara Time (UTC+04)",4],
	["SAST","South African Standard Time (UTC+02)",2],
	["SBT","Solomon Islands Time (UTC+11)",11],
	["SCT","Seychelles Time (UTC+04)",4],
	["SGT","Singapore Time (UTC+08)",8],
	["SLT","Sri Lanka Time (UTC+05:30)",5.5],
	["SRT","Suriname Time (UTC-03)",-3],
	["SST","Samoa Standard Time (UTC-11)",-11],
	["SST","Singapore Standard Time (UTC+08)",8],
	["SYOT","Showa Station Time (UTC+03)",3],
	["TAHT","Tahiti Time (UTC-10)",-10],
	["THA","Thailand Standard Time (UTC+07)",7],
	["TFT","Indian/Kerguelen (UTC+05)",5],
	["TJT","Tajikistan Time (UTC+05)",5],
	["TKT","Tokelau Time (UTC+14)",14],
	["TLT","Timor Leste Time (UTC+09)",9],
	["TMT","Turkmenistan Time (UTC+05)",5],
	["TOT","Tonga Time (UTC+13)",13],
	["TVT","Tuvalu Time (UTC+12)",12],
	["UCT","Coordinated Universal Time (UTC)",0],
	["ULAT","Ulaanbaatar Time (UTC+08)",8],
	["UTC","Coordinated Universal Time (UTC)",0],
	["UYST","Uruguay Summer Time (UTC-02)",-2],
	["UYT","Uruguay Standard Time (UTC-03)",-3],
	["UZT","Uzbekistan Time (UTC+05)",5],
	["VET","Venezuelan Standard Time (UTC-04:30)",-4.5],
	["VLAT","Vladivostok Time (UTC+10)",10],
	["VOLT","Volgograd Time (UTC+04)",4],
	["VOST","Vostok Station Time (UTC+06)",6],
	["VUT","Vanuatu Time (UTC+11)",11],
	["WAKT","Wake Island Time (UTC+12)",12],
	["WAST","West Africa Summer Time (UTC+02)",2],
	["WAT","West Africa Time (UTC+01)",1],
	["WEDT","Western European Daylight Time (UTC+01)",1],
	["WEST","Western European Summer Time (UTC+01)",1],
	["WET","Western European Time (UTC)",0],
	["WST","Western Standard Time (UTC+08)",8],
	["YAKT","Yakutsk Time (UTC+09)",9],
	["YEKT","Yekaterinburg Time (UTC+05)",5],
];